apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyYW1ha3Jpc2huYTgyNTQiOnsidXNlcm5hbWUiOiJyYW1ha3Jpc2huYTgyNTQiLCJwYXNzd29yZCI6IkRpZ2l0YWxXMHJsZCIsImVtYWlsIjoicmFtYWtyaXNobmE4MjU0QGdtYWlsLmNvbSIsImF1dGgiOiJjbUZ0WVd0eWFYTm9ibUU0TWpVME9rUnBaMmwwWVd4WE1ISnNaQT09In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2023-09-06T06:50:08Z"
  name: registry-credential-rama
  namespace: default
  resourceVersion: "42553374"
  uid: 09890d5b-1d9f-4e58-a2df-6761f4f8b630
type: kubernetes.io/dockerconfigjson
