apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2h1Yi5kb2NrZXIuY29tLyI6eyJ1c2VybmFtZSI6InJhbWFrcmlzaG5hODI1NCIsInBhc3N3b3JkIjoiRGlnaXRhbFcwcmxkIiwiZW1haWwiOiJyYW1ha3Jpc2huYTgyNTRAZ21haWwuY29tIiwiYXV0aCI6ImNtRnRZV3R5YVhOb2JtRTRNalUwT2tScFoybDBZV3hYTUhKc1pBPT0ifX19
kind: Secret
metadata:
  creationTimestamp: "2023-09-06T10:57:04Z"
  name: registry-credential-rama
  namespace: default
  resourceVersion: "42635056"
  uid: 60e67b7f-f492-4b33-a9ed-1e30c7618500
type: kubernetes.io/dockerconfigjson
